build:
  uv run sphinx-build -M html source build
  rm -rf ../www/public/docs
  cp -r build/html ../www/public/docs

fmt:
  prettier --write .

generate-api-docs:
  uv run sphinx-apidoc -o source ../src
